COALLOAD_Screens {
 m_aImages {
  "{50BC49DEC750B414}UI/images/LoadingScreens/loading_screen_10_BC.edds"
  "{55498A192C024EA2}UI/images/LoadingScreens/loading_screen_11_BC.edds"
  "{5B57CE5111F54178}UI/images/LoadingScreens/loading_screen_12_BC.edds"
  "{5EA20D96FAA7BBCE}UI/images/LoadingScreens/loading_screen_13_BC.edds"
  "{476B46C16A1B5ECC}UI/images/LoadingScreens/loading_screen_14_BC.edds"
  "{429E85068149A47A}UI/images/LoadingScreens/loading_screen_15_BC.edds"
  "{4C80C14EBCBEABA0}UI/images/LoadingScreens/loading_screen_16_BC.edds"
  "{4975028957EC5116}UI/images/LoadingScreens/loading_screen_17_BC.edds"
  "{7AE7942676959B12}UI/images/LoadingScreens/loading_screen_19_BC.edds"
  "{9EAEB77BB1FC5680}UI/images/LoadingScreens/loading_screen_1_BC.edds"
  "{104C68FB714C3653}UI/images/LoadingScreens/loading_screen_20_BC.edds"
  "{15B9AB3C9A1ECCE5}UI/images/LoadingScreens/loading_screen_21_BC.edds"
  "{1BA7EF74A7E9C33F}UI/images/LoadingScreens/loading_screen_22_BC.edds"
  "{079B67E4DC07DC8B}UI/images/LoadingScreens/loading_screen_24_BC.edds"
  "{026EA4233755263D}UI/images/LoadingScreens/loading_screen_25_BC.edds"
  "{0C70E06B0AA229E7}UI/images/LoadingScreens/loading_screen_26_BC.edds"
  "{098523ACE1F0D351}UI/images/LoadingScreens/loading_screen_27_BC.edds"
  "{3FE276C42BDBE3E3}UI/images/LoadingScreens/loading_screen_28_BC.edds"
  "{3A17B503C0891955}UI/images/LoadingScreens/loading_screen_29_BC.edds"
  "{90B0F3338C0B595A}UI/images/LoadingScreens/loading_screen_2_BC.edds"
  "{EBB9EB796F4CA0A9}UI/images/LoadingScreens/loading_screen_31_BC.edds"
  "{E0526CF6B9E955C5}UI/images/LoadingScreens/loading_screen_33_BC.edds"
  "{F99B27A12955B0C7}UI/images/LoadingScreens/loading_screen_34_BC.edds"
  "{FC6EE466C2074A71}UI/images/LoadingScreens/loading_screen_35_BC.edds"
  "{F270A02EFFF045AB}UI/images/LoadingScreens/loading_screen_36_BC.edds"
  "{F78563E914A2BF1D}UI/images/LoadingScreens/loading_screen_37_BC.edds"
  "{C1E23681DE898FAF}UI/images/LoadingScreens/loading_screen_38_BC.edds"
  "{C417F54635DB7519}UI/images/LoadingScreens/loading_screen_39_BC.edds"
  "{91AC2AB01D7532DD}UI/images/LoadingScreens/loading_screen_40_BC.edds"
  "{8C8C7BA3F7E546EE}UI/images/LoadingScreens/loading_screen_4_BC.edds"
  "{8979B8641CB7BC58}UI/images/LoadingScreens/loading_screen_5_BC.edds"
  "{8767FC2C2140B382}UI/images/LoadingScreens/loading_screen_6_BC.edds"
  "{82923FEBCA124934}UI/images/LoadingScreens/loading_screen_7_BC.edds"
  "{B4F56A8300397986}UI/images/LoadingScreens/loading_screen_8_BC.edds"
  "{B100A944EB6B8330}UI/images/LoadingScreens/loading_screen_9_BC.edds"
  "{9459E977F627C86B}UI/images/LoadingScreens/loading_screen_41_BC.edds"
  "{9A47AD3FCBD0C7B1}UI/images/LoadingScreens/loading_screen_42_BC.edds"
  "{9FB26EF820823D07}UI/images/LoadingScreens/loading_screen_43_BC.edds"
  "{867B25AFB03ED805}UI/images/LoadingScreens/loading_screen_44_BC.edds"
 }
}